<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Sensor;
use App\Models\Farm;
use App\Models\ActivityLog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Sensor/device registration and farm assignment. device_key (the
 * physical device's burned-in identity, matched against every
 * SensorIngestController::store() POST) is set once at creation and never
 * editable afterward, same as sensor_code.
 *
 * `label` is the Admin-facing "Device Name" (e.g. AGB-D01). It identifies
 * the PHYSICAL unit, not the farm: the two thesis devices rotate across
 * ten farms, so the name is entered once at registration and never
 * changes when the device is moved. Devices registered without a label
 * (older rows) fall back to their auto-generated sensor_code for display.
 * Every "Device Name" field in the system (Devices tab, Farm Information
 * > Sensor & Monitoring, the Farms list table) reads from this same
 * Sensor record.
 *
 * A device's farm_id is only its CURRENT assignment. Readings copy the
 * farm_id at ingestion time, so assign()/unassign() never touch historical
 * sensor_readings — Week 1 readings stay with the Week 1 farm.
 */
class SensorController extends Controller
{
    /**
     * Every registered device, including unassigned ones — the place to
     * find a device that is between farms so it can be assigned again.
     */
    public function all()
    {
        $sensors = Sensor::with('farm:id,farm_name')
            ->orderBy('label')
            ->orderBy('sensor_code')
            ->get()
            ->map(fn($s) => $this->serialize($s));

        return response()->json(['success' => true, 'data' => $sensors]);
    }

    /**
     * List sensors currently assigned to a specific farm — powers the
     * Devices tab on the Farm Details page.
     */
    public function index(int $farmId)
    {
        Farm::findOrFail($farmId);

        $sensors = Sensor::with('farm:id,farm_name')
            ->where('farm_id', $farmId)
            ->latest('installed_at')
            ->get()
            ->map(fn($s) => $this->serialize($s));

        return response()->json(['success' => true, 'data' => $sensors]);
    }

    public function store(Request $request)
    {
        $request->validate([
            // Nullable: a device can be registered first and assigned later.
            'farm_id'      => 'nullable|exists:farms,id',
            'device_key'   => 'required|string|unique:sensors,device_key',
            'label'        => 'nullable|string|max:50|unique:sensors,label',
            'installed_at' => 'nullable|date',
            'status'       => 'nullable|in:Active,Inactive',
        ]);

        $sensor = Sensor::create([
            'farm_id'      => $request->farm_id,
            'device_key'   => $request->device_key,
            'label'        => $request->label ?: null,
            'installed_at' => $request->installed_at,
            'status'       => $request->status ?? 'Active',
            // sensor_code is auto-generated by Sensor::booted().
        ]);

        $farm = $request->farm_id ? Farm::find($request->farm_id) : null;

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Registered Sensor',
            'details' => "Registered device {$sensor->device_name} ({$sensor->device_key})"
                . ($farm ? " for {$farm->farm_name}" : ' (unassigned)'),
            'type'    => 'Farm',
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Device registered successfully.',
            'data'    => $this->serialize($sensor->load('farm:id,farm_name')),
        ]);
    }

    /**
     * Only status is editable here — device_key, sensor_code, and the
     * permanent label (Device Name) are all fixed once set. Farm changes go
     * through assign()/unassign() so they are logged as such.
     */
    public function update(Request $request, int $id)
    {
        $sensor = Sensor::findOrFail($id);

        $request->validate([
            'status' => 'required|in:Active,Inactive',
        ]);

        $sensor->update(['status' => $request->status]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Updated Sensor',
            'details' => "Updated device {$sensor->device_name}",
            'type'    => 'Farm',
        ]);

        return response()->json(['success' => true, 'message' => 'Device updated successfully.']);
    }

    /**
     * Assign (or move) a device to a farm. Covers both a first assignment
     * and a reassignment — the device row is updated in place, never
     * recreated, so device_key and label are untouched. A farm may hold
     * more than one device (existing hasMany behaviour), so the only
     * conflict rejected is assigning a device to the farm it is already on.
     */
    public function assign(Request $request, int $id)
    {
        $sensor = Sensor::findOrFail($id);

        $request->validate([
            'farm_id' => 'required|exists:farms,id',
        ]);

        $farm = Farm::findOrFail($request->farm_id);

        if ($sensor->farm_id === $farm->id) {
            return response()->json([
                'success' => false,
                'message' => "Device {$sensor->device_name} is already assigned to {$farm->farm_name}.",
            ], 422);
        }

        $previous = $sensor->farm;

        $sensor->update(['farm_id' => $farm->id]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => $previous ? 'Reassigned Sensor' : 'Assigned Sensor',
            'details' => $previous
                ? "Moved device {$sensor->device_name} from {$previous->farm_name} to {$farm->farm_name}"
                : "Assigned device {$sensor->device_name} to {$farm->farm_name}",
            'type'    => 'Farm',
        ]);

        return response()->json([
            'success' => true,
            'message' => "Device assigned to {$farm->farm_name}.",
            'data'    => $this->serialize($sensor->fresh('farm:id,farm_name')),
        ]);
    }

    /**
     * End the current farm assignment without deleting the device. The
     * farm drops back to "Pending Setup"; the device keeps its key, name and
     * history and can be assigned to the next farm via assign().
     */
    public function unassign(int $id)
    {
        $sensor = Sensor::findOrFail($id);

        if (!$sensor->farm_id) {
            return response()->json([
                'success' => false,
                'message' => "Device {$sensor->device_name} is not assigned to any farm.",
            ], 422);
        }

        $previous = $sensor->farm;

        $sensor->update(['farm_id' => null]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Unassigned Sensor',
            'details' => "Removed device {$sensor->device_name} from {$previous->farm_name}",
            'type'    => 'Farm',
        ]);

        return response()->json([
            'success' => true,
            'message' => "Device removed from {$previous->farm_name}.",
            'data'    => $this->serialize($sensor->fresh('farm:id,farm_name')),
        ]);
    }

    private function serialize(Sensor $s): array
    {
        return [
            'id'           => $s->id,
            'device_name'  => $s->device_name,
            'label'        => $s->label,
            'device_key'   => $s->device_key,
            'sensor_code'  => $s->sensor_code,
            'status'       => $s->status,
            'farm_id'      => $s->farm_id,
            'farm_name'    => $s->farm?->farm_name,
            'connectivity' => $s->connectivity(),
            'installed_at' => $s->installed_at?->format('M d, Y'),
            'last_seen_at' => $s->last_seen_at?->format('M d, Y g:i A'),
        ];
    }
}
