<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Sensor;
use App\Models\Farm;
use App\Models\ActivityLog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Support\LocalTime;

/**
 * Sensor/device registration and farm assignment. device_key (the
 * physical device's burned-in identity, matched against every
 * SensorIngestController::store() POST) is set once at creation and never
 * editable afterward, same as sensor_code.
 *
 * `label` is the Admin-facing "Device Name" (e.g. AGB-D01). It identifies
 * the PHYSICAL unit, not the farm, so it is entered once at registration
 * and never changes. Devices registered without a label (older rows) fall
 * back to their auto-generated sensor_code for display. Every "Device Name"
 * field in the system (Devices tab, Farm Information > Sensor & Monitoring,
 * the Farms list table) reads from this same Sensor record.
 *
 * Business model: each farm owner buys and owns the device installed on
 * their farm, so a device normally stays on one farm for its whole life.
 * A farm therefore holds at most ONE Active assigned device at a time —
 * enforced by assign(); registration always leaves a device Unassigned.
 * Inactive devices (damaged/retired but not yet unassigned) do not block a
 * replacement, matching how FarmStatusService only counts Active devices.
 *
 * A device's farm_id is only its CURRENT assignment. Readings copy the
 * farm_id at ingestion time, so assign()/unassign() never touch historical
 * sensor_readings — a replaced device's old readings keep both their
 * original farm_id and their original sensor_id.
 */
class SensorController extends Controller
{
    /**
     * Every registered device, including unassigned ones — the place to
     * find a device that is between farms so it can be assigned again.
     */
    public function all()
    {
        $sensors = Sensor::with('farm:id,farm_name')
            ->orderBy('label')
            ->orderBy('sensor_code')
            ->get()
            ->map(fn($s) => $this->serialize($s));

        return response()->json(['success' => true, 'data' => $sensors]);
    }

    /**
     * List sensors currently assigned to a specific farm — powers the
     * Devices tab on the Farm Details page.
     */
    public function index(int $farmId)
    {
        Farm::findOrFail($farmId);

        $sensors = Sensor::with('farm:id,farm_name')
            ->where('farm_id', $farmId)
            ->latest('installed_at')
            ->get()
            ->map(fn($s) => $this->serialize($s));

        return response()->json(['success' => true, 'data' => $sensors]);
    }

    /**
     * The characters a Device Key may contain after the AGB- prefix.
     *
     * Deliberately omits 0/O and 1/I/L — those are what people misread when
     * copying a key by hand, and a misread key means a 401 at ingestion.
     * Matching the provisioning command's alphabet exactly means a typo like
     * O-for-0 is caught here, at registration, instead of silently producing
     * a device that can never authenticate.
     *
     * @see \App\Console\Commands\ProvisionDevice
     */
    private const KEY_PATTERN = '/^AGB-[ABCDEFGHJKMNPQRSTUVWXYZ23456789]{8}$/';

    /**
     * Registers a physical device that has ALREADY been provisioned.
     *
     * The Device Key is minted beforehand by
     * `php artisan agribantay:provision-device` and flashed into that unit's
     * firmware before turnover. It is submitted here and saved exactly as
     * given — never regenerated, never altered — because the firmware is
     * already using it and the two must match for ingestion to work.
     *
     * A new device is always Unassigned. The LGU assigns it to a farm after
     * turnover via assign(), which is where the one-Active-device-per-farm
     * rule is enforced.
     */
    public function store(Request $request)
    {
        $request->validate([
            'device_key'   => [
                'required', '',
                'regex:' . self::KEY_PATTERN,
                'unique:sensors,device_key',
            ],
            'label'        => 'nullable|string|max:50|unique:sensors,label',
            'installed_at' => 'nullable|date',
        ], [
            'device_key.regex'  => 'The device key must look like AGB-XXXXXXXX, using capital letters and numbers only (no O, I, L, 0 or 1). Use the key from the provisioning command.',
            'device_key.unique' => 'That device key is already registered to another device.',
        ]);

        $sensor = Sensor::create([
            'farm_id'      => null,                            // always Unassigned
            'device_key'   => $request->device_key,            // saved exactly as submitted
            'label'        => $request->label ?: null,
            'installed_at' => $request->installed_at,
            'status'       => 'Active',
            // sensor_code is auto-generated by Sensor::booted().
        ]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Registered Sensor',
            // The Device Name and sensor_code identify the unit well enough
            // here. The full device_key is a credential — anything holding it
            // can post readings as this device — so it never goes into the
            // Activity Logs, which are readable outside the Devices tab.
            'details' => "Registered device {$sensor->device_name} ({$sensor->sensor_code}) (unassigned)",
            'type'    => 'Farm',
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Device registered successfully.',
            'data'    => $this->serialize($sensor->load('farm:id,farm_name')),
        ]);
    }

    /**
     * Only status is editable here — device_key, sensor_code, and the
     * permanent label (Device Name) are all fixed once set. Farm changes go
     * through assign()/unassign() so they are logged as such.
     */
    public function update(Request $request, int $id)
    {
        $sensor = Sensor::findOrFail($id);

        $request->validate([
            'status' => 'required|in:Active,Inactive',
        ]);

        $sensor->update(['status' => $request->status]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Updated Sensor',
            'details' => "Updated device {$sensor->device_name}",
            'type'    => 'Farm',
        ]);

        return response()->json(['success' => true, 'message' => 'Device updated successfully.']);
    }

    /**
     * Assign a device to a farm — the device row is updated in place, never
     * recreated, so device_key and label are untouched.
     *
     * Under the owner-buys-their-own-device model this is normally used to
     * put a repaired or replacement device back on its own farm. It also
     * still supports moving a device between farms, which the thesis data-
     * collection rotation (2 devices across 10 farms) depends on. There is
     * no Reassign button in the UI; this stays an Admin/Super Admin-only
     * endpoint, so ordinary Farm Owners can never reach it.
     *
     * Rejected: assigning to the farm the device is already on, and
     * assigning an Active device to a farm that already has one.
     */
    public function assign(Request $request, int $id)
    {
        $sensor = Sensor::findOrFail($id);

        $request->validate([
            'farm_id' => 'required|exists:farms,id',
        ]);

        $farm = Farm::findOrFail($request->farm_id);

        if ($sensor->farm_id === $farm->id) {
            return response()->json([
                'success' => false,
                'message' => "Device {$sensor->device_name} is already assigned to {$farm->farm_name}.",
            ], 422);
        }

        // A farm may hold several devices at once: one poultry house gets one
        // unit, and a farm can have several houses. An earlier rule allowed
        // only one active device per farm and is deliberately gone — it made
        // a multi-house farm impossible to monitor.
        //
        // What still holds: one device reports for one place. Two units in the
        // same house would interleave into a single stream for that spot, and
        // nothing here can tell them apart, so the LGU is responsible for
        // installing one per house.

        $previous = $sensor->farm;

        $sensor->update(['farm_id' => $farm->id]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => $previous ? 'Reassigned Sensor' : 'Assigned Sensor',
            'details' => $previous
                ? "Moved device {$sensor->device_name} from {$previous->farm_name} to {$farm->farm_name}"
                : "Assigned device {$sensor->device_name} to {$farm->farm_name}",
            'type'    => 'Farm',
        ]);

        return response()->json([
            'success' => true,
            'message' => "Device assigned to {$farm->farm_name}.",
            'data'    => $this->serialize($sensor->fresh('farm:id,farm_name')),
        ]);
    }

    /**
     * End the current farm assignment without deleting the device. The
     * farm drops back to "Pending Setup"; the device keeps its key, name and
     * history and can be assigned to the next farm via assign().
     */
    public function unassign(int $id)
    {
        $sensor = Sensor::findOrFail($id);

        if (!$sensor->farm_id) {
            return response()->json([
                'success' => false,
                'message' => "Device {$sensor->device_name} is not assigned to any farm.",
            ], 422);
        }

        $previous = $sensor->farm;

        $sensor->update(['farm_id' => null]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Unassigned Sensor',
            'details' => "Removed device {$sensor->device_name} from {$previous->farm_name}",
            'type'    => 'Farm',
        ]);

        return response()->json([
            'success' => true,
            'message' => "Device removed from {$previous->farm_name}.",
            'data'    => $this->serialize($sensor->fresh('farm:id,farm_name')),
        ]);
    }

    /**
     * The farm's current Active device, if any — one farm monitors with one
     * device. Inactive devices are ignored so a damaged unit that has not
     * been unassigned yet never blocks its own replacement.
     */
    private function serialize(Sensor $s): array
    {
        return [
            'id'           => $s->id,
            'device_name'  => $s->device_name,
            'label'        => $s->label,
            'device_key'   => $s->device_key,
            'sensor_code'  => $s->sensor_code,
            'status'       => $s->status,
            'farm_id'      => $s->farm_id,
            'farm_name'    => $s->farm?->farm_name,
            'connectivity' => $s->connectivity(),
            'installed_at' => $s->installed_at?->format('M d, Y'),
            'last_seen_at' => LocalTime::dateTime($s->last_seen_at),
        ];
    }
}
