<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Sensor;
use App\Models\Farm;
use App\Models\ActivityLog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Sensor/device registration — previously nonexistent. device_key (the
 * physical device's burned-in identity, matched against every
 * SensorIngestController::store() POST) is set once at creation and never
 * editable afterward, same as sensor_code.
 *
 * `label` is the Admin-facing "Device Name". It is entirely system-generated
 * (see Sensor::generateDeviceName()) from the farm's id + installation date
 * and is never accepted from the request — there is no manual-entry path,
 * by design, since a free-typed name could collide or be left inconsistent.
 * It falls back to the older date-only sensor_code (e.g. SFN180726) only
 * for the handful of sensors that predate this generation scheme. This is
 * the single source of truth for a farm's device name: every "Device Name"
 * field in the system (Devices tab, Farm Information > Sensor & Monitoring,
 * the Farms list table) reads from this same Sensor record.
 */
class SensorController extends Controller
{
    /**
     * List sensors for a specific farm — powers the Devices tab on the
     * Farm Details page.
     */
    public function index(int $farmId)
    {
        Farm::findOrFail($farmId);

        $sensors = Sensor::where('farm_id', $farmId)
            ->latest('installed_at')
            ->get()
            ->map(fn($s) => [
                'id'            => $s->id,
                'device_name'   => $s->label ?: $s->sensor_code,
                'label'         => $s->label,
                'device_key'    => $s->device_key,
                'sensor_code'   => $s->sensor_code,
                'status'        => $s->status,
                'installed_at'  => $s->installed_at?->format('M d, Y'),
                'last_seen_at'  => $s->updated_at?->format('M d, Y g:i A'),
            ]);

        return response()->json(['success' => true, 'data' => $sensors]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'farm_id'      => 'required|exists:farms,id',
            'device_key'   => 'required|string|unique:sensors,device_key',
            'installed_at' => 'nullable|date',
            'status'       => 'nullable|in:Active,Inactive',
        ]);

        $sensor = Sensor::create([
            'farm_id'      => $request->farm_id,
            'device_key'   => $request->device_key,
            'installed_at' => $request->installed_at,
            'status'       => $request->status ?? 'Active',
            // sensor_code and label (Device Name) are both auto-generated by
            // Sensor::booted() — left out here so that logic isn't duplicated
            // and so there is no path to a manually-typed Device Name.
        ]);

        $farm = Farm::find($request->farm_id);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Registered Sensor',
            'details' => "Registered device {$sensor->sensor_code} ({$sensor->device_key}) for {$farm->farm_name}",
            'type'    => 'Farm',
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Device registered successfully.',
            'data'    => [
                'id'           => $sensor->id,
                'device_name'  => $sensor->label ?: $sensor->sensor_code,
                'device_key'   => $sensor->device_key,
                'sensor_code'  => $sensor->sensor_code,
                'status'       => $sensor->status,
                'installed_at' => $sensor->installed_at->format('M d, Y'),
            ],
        ]);
    }

    /**
     * Only status is editable here — device_key, sensor_code, and the
     * system-generated label (Device Name) are all permanent once set.
     */
    public function update(Request $request, int $id)
    {
        $sensor = Sensor::findOrFail($id);

        $request->validate([
            'status' => 'required|in:Active,Inactive',
        ]);

        $sensor->update(['status' => $request->status]);

        ActivityLog::create([
            'user_id' => Auth::id(),
            'role'    => Auth::user()->role,
            'action'  => 'Updated Sensor',
            'details' => "Updated device {$sensor->sensor_code}",
            'type'    => 'Farm',
        ]);

        return response()->json(['success' => true, 'message' => 'Device updated successfully.']);
    }
}