<?php

namespace App\Http\Controllers\Vet;

use App\Http\Controllers\Controller;
use App\Models\GeneratedReport;
use App\Services\GeneratedReportService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class GeneratedReportController extends Controller
{
    public function __construct(private GeneratedReportService $reports) {}

    /**
     * The Vet generates its own archives. Same period rules and the same
     * snapshot builder the Admin endpoint uses — what differs is only who
     * owns the result and, on read, which slice of it is returned (see
     * show()). Kept as a thin delegation so the two can never drift.
     */
    public function store(Request $request, \App\Http\Controllers\Admin\GeneratedReportController $admin)
    {
        return $admin->store($request);
    }

    /**
     * The Vet may remove its own archives, by the same ownership rule the Admin
     * controller applies — and it is that controller's check that runs, since
     * this delegates rather than repeating it. A report generated by anyone
     * else 404s.
     */
    public function destroy(GeneratedReport $generatedReport, \App\Http\Controllers\Admin\GeneratedReportController $admin)
    {
        return $admin->destroy($generatedReport);
    }

    public function index()
    {
        // The Vet sees only the archives the Vet generated. Mirrors the rule
        // in Admin\GeneratedReportController: one table serves every module,
        // so without this a staff member's report appeared here too.
        $reports = GeneratedReport::where('generated_by_id', Auth::id())
            ->orderByDesc('created_at')
            ->orderByDesc('id')
            ->get()
            ->map(fn ($r) => [
                'id' => $r->id,
                'report_name' => $r->report_name,
                'period_label' => $this->reports->periodLabel($r->period_start, $r->period_end),
                'period_start' => $r->period_start->toDateString(),
                'report_type' => $r->report_type,
                'date_generated' => $this->reports->generatedLabel($r->created_at, false),
            ]);

        return response()->json(['success' => true, 'data' => $reports]);
    }

    public function show(GeneratedReport $generatedReport)
    {
        if ($generatedReport->generated_by_id !== Auth::id()) {
            abort(404);
        }

        $snapshot = $generatedReport->snapshot ?? [];

        return response()->json([
            'success' => true,
            'data' => [
                'id' => $generatedReport->id,
                'report_name' => $generatedReport->report_name,
                'period_label' => $this->reports->periodLabel($generatedReport->period_start, $generatedReport->period_end),
                'report_type' => $generatedReport->report_type,
                'date_generated' => $this->reports->generatedLabel($generatedReport->created_at),
                'snapshot' => [
                    // Who prepared and who notes the report — the same two
                    // lines every other report view prints, and not Admin data.
                    'signatures' => $snapshot['signatures'] ?? null,
                    'vet_summary' => $snapshot['vet_summary'] ?? [],
                    'vet_services' => $snapshot['vet_services'] ?? [],
                    // Only the veterinary slice of the period activity block is
                    // forwarded. The rest of it counts inspections, alerts,
                    // clean-outs and odor/fly service requests, which are Admin
                    // scope and must not reach a Vet — same boundary the two keys
                    // above already enforce. Absent on snapshots archived before
                    // period_activity existed, and the report view treats it as
                    // optional.
                    'period_activity' => isset($snapshot['period_activity'])
                        ? [
                            'vet_services_completed' => $snapshot['period_activity']['vet_services_completed'] ?? null,
                            'vet_farms_covered' => $snapshot['period_activity']['vet_farms_covered'] ?? null,
                        ]
                        : null,
                ],
            ],
        ]);
    }
}
